server:
  port: 8083

spring:
  application:
    name: SERVICE-CLIENT
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/clients
    username: ilyas
    password: ilyas
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
      enabled: true
